server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/temperatureapp
    username: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: test.springboot.cns@gmail.com
    password: swubgbtzvftqflcw

    properties:
      mail:
        smtp:
          ssl:
#            trust: "*"
          auth: true
          starttls:
            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000
